name = "McPack"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3eadcec0dd80645b56542efbb920735a86a8ed4582f7d376687811f1c304ef07"

[versions]
fabric = "0.17.3"
minecraft = "1.20.1"
