name = "McPack"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3210878239316abfc9a5867a30e1bdbd6aa331bc0e459d7dc288e3a0ac7e79d0"

[versions]
fabric = "0.17.3"
minecraft = "1.20.1"
